import { useState, useEffect } from "react";
import ReactMarkdown from "react-markdown";
import styles from "./SopDocument.module.css";

export default function SopDocument({ content, title }) {
  const [isEditMode, setIsEditMode] = useState(false);
  const [editedContent, setEditedContent] = useState(content || "");
  const [isExporting, setIsExporting] = useState(false);

  useEffect(() => {
    setEditedContent(content || "");
  }, [content]);

  if (!content) {
    return (
      <div className={styles.noContent}>
        Document will be generated after simulation completes.
      </div>
    );
  }

  const handleDownloadMd = () => {
    const blob = new Blob([editedContent], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${title.replace(/\s+/g, "_").toLowerCase()}_${new Date().toISOString().split("T")[0]}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleDownloadDocx = async () => {
    try {
      setIsExporting(true);
      const res = await fetch("/api/export/docx", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ markdown: editedContent, title }),
      });
      
      if (!res.ok) throw new Error("Export failed");
      
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${title.replace(/\s+/g, "_").toLowerCase()}_${new Date().toISOString().split("T")[0]}.docx`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error(err);
      alert("Failed to export DOCX. Ensure backend is running and reachable.");
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <div className={styles.sopContainer}>
      {/* AI Hallucination Warning Banner */}
      <div className={styles.aiBanner}>
        <span className={styles.aiBannerIcon}>⚠️</span>
        <div className={styles.aiBannerText}>
          <strong>AI-Generated Draft — Please Review Before Use</strong>
          <span>
            This document was automatically generated by Gemini AI. Hallucination (incorrect content generation) may occur.
            Please have a domain expert review and revise the content before conducting any experiments.
          </span>
        </div>
        <button
          className={styles.downloadDocxPrimary}
          onClick={handleDownloadDocx}
          disabled={isExporting}
          title="Download as editable Word file"
        >
          {isExporting ? (
            <span className={styles.exportingSpinner}>⏳</span>
          ) : (
            <>
              <span className={styles.docxIcon}>📄</span>
              <span>.docx Download</span>
            </>
          )}
        </button>
      </div>

      <div className={styles.toolbar}>
        <span className={styles.toolbarTitle}>{title}</span>
        
        <div className={styles.toolbarActions}>
          <div className={styles.modeToggle}>
            <button 
              className={`${styles.toggleBtn} ${!isEditMode ? styles.active : ""}`}
              onClick={() => setIsEditMode(false)}
            >
              👁 Preview
            </button>
            <button 
              className={`${styles.toggleBtn} ${isEditMode ? styles.active : ""}`}
              onClick={() => setIsEditMode(true)}
            >
              ✏️ Edit
            </button>
          </div>

          <div className={styles.downloadGroup}>
            <button className={styles.downloadBtn} onClick={handleDownloadMd}
              title="Download as Markdown file">
              ⬇ .MD
            </button>
            <button 
              className={`${styles.downloadBtn} ${styles.downloadDocx}`} 
              onClick={handleDownloadDocx}
              disabled={isExporting}
              title="Download as Word file"
            >
              {isExporting ? "⏳..." : "⬇ .DOCX"}
            </button>
          </div>
        </div>
      </div>

      <div className={styles.documentFrame}>
        {isEditMode ? (
          <>
            <div className={styles.editModeNote}>
              ✏️ You can edit the content directly here. Your edits will be reflected in the downloaded .DOCX file.
            </div>
            <textarea
              className={styles.editorTextarea}
              value={editedContent}
              onChange={(e) => setEditedContent(e.target.value)}
              spellCheck="false"
            />
          </>
        ) : (
          <div className={styles.markdownContent}>
            <ReactMarkdown>{editedContent}</ReactMarkdown>
          </div>
        )}
      </div>
    </div>
  );
}
